on: [push]

jobs:
  anchore_job:
    runs-on: ubuntu-latest
    name: Anchore scan directory
    steps:
    - name: Scan current project
      id: scan
      uses: anchore/scan-action@v2
      with:
        path: "."
        fail-build: true
